<?php

########################################################################
# Extension Manager/Repository config file for ext: "mn_google_plus"
#
# Auto generated by Extension Builder 2012-01-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google plus',
	'description' => 'Get your recent activities and updates from Google Plus when logged in as a fe_user.',
	'category' => 'plugin',
	'author' => 'Mattias Nilsson',
	'author_email' => 'tollepjaer@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
            't3jquery' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>